# Site settings
title: Michael Pederson
tag_text: Michael Pederson
description: Builder and collaborator, crafting delightful iOS user experiences, delivering products to market for 10 years. I focus on user outcomes, usable interfaces, clean code, and working software. I have worked with all kinds of clients, from lone individuals, small and large startups, to Fortune 100 companies, and my work has been included in acquisitions by Google, Amazon, and Microsoft.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
